---
title: 'COVID-19 Projections for Colorado'
author: ""
date: "March 24, 2020"
output:
  html_document: default
  fig_caption: yes
  number_sections: yes
  word_document: default
  pdf_document: default
---



```{r, echo = F, message = F, warning = F}
op <- par()
options(width=80)
#emptyenv()
rm(list=ls())

library(knitr)
setwd('/Users/katiecolborn/OneDrive - The University of Colorado Denver/COVID19/Code')

dat <- read.csv('./allscenarios5.csv')

dat$date <- as.Date(dat$time, format="%m/%d/%Y", origin="01/21/2020")

dat$R0a <- ifelse(dat$R0==3, "R0=3", "R0=4")
```


```{r, echo = F, message = F, warning = F}
#dat2 <- subset(dat, R0==3)

library(ggplot2)
require(scales)
#pdf('./infections.pdf')
ggplot(data = dat) +
  geom_line(mapping = aes(x = date, y = I, color = as.factor(mag))) +
  facet_wrap(. ~ R0a) +
  ggtitle("Symptomatic Infections") +
  scale_y_continuous(labels = comma, breaks = scales::pretty_breaks(n = 10)) +
  ylab("Symptomatic Infections") +
  xlab("Date") +
  labs(color="Social Distancing") +
  scale_x_date(date_labels="%b %y",date_breaks  ="2 month") +
  theme(legend.position="bottom", legend.box = "horizontal", axis.text.x = element_text(angle = 90), panel.background = element_blank(), legend.key=element_blank())
#invisible(dev.off())

ggplot(data = dat) +
  geom_line(mapping = aes(x = date, y = Ih, color = as.factor(mag))) +
  ggtitle("Hospitalizations") + 
  facet_wrap(. ~ R0a) +
  scale_y_continuous(labels = comma, breaks = scales::pretty_breaks(n = 10)) +
  ylab("Hospitalizations") +
  xlab("Date") +
  labs(color="Social Distancing") +
  scale_x_date(date_labels="%b %y",date_breaks  ="2 month") +
  theme(legend.position="bottom", legend.box = "horizontal", axis.text.x = element_text(angle = 90), panel.background = element_blank(), legend.key=element_blank())
```

For critical care plots, the red horizontal lines indicate 709 ICU beds, 1709 ICU beds and 4291 ICU beds. We assume that 709 beds are not in use currently (out of the ~1400 total across the state). We further assume that 1709 beds will be available (due to expansion) by late April, and 4291 after that.  

```{r, echo = F, message = F, warning = F}

ggplot(data = dat) +
  geom_hline(yintercept=709, linetype="dashed", color = "red") +
  geom_hline(yintercept=1709, linetype="dashed", color = "red") +
  geom_hline(yintercept=4291, linetype="dashed", color = "red") +
  geom_line(mapping = aes(x = date, y = Ic, color = as.factor(mag))) +
  ggtitle("Critical Care") +
  facet_wrap(. ~ R0a) +
  scale_y_continuous(labels = comma, breaks = scales::pretty_breaks(n = 10)) +
  ylab("Critical Care") +
  xlab("Date") +
  labs(color="Social Distancing Implemented") +
  scale_x_date(date_labels="%b %y",date_breaks  ="2 month") +
  theme(legend.position="bottom", legend.box = "horizontal", axis.text.x = element_text(angle = 90), panel.background = element_blank(), legend.key=element_blank())


```



